boostcampwm-2022/web18-PRV

.github/workflows/deploy_dev.yml
.gitignore
backend/Dockerfile
frontend/.dockerignore
frontend/Dockerfile
frontend/nginx.conf

* URL
* FE: http://49.50.172.204
* BE: http://49.50.172.204:3001
1. dev 브랜치 push(또는 pr merge)
2. `deploy_dev.yml` 에서 작성된 job들이 실행됨.
* Naver Container Registry에 도커 이미지 push 
* BE build, push
* FE build, push
* ssh로 dev용 서버에 접속, Naver Container Registry로부터 FE, BE 이미지 각각 pull & run
> production 용 자동화를 만들려면, 접속할 ssh 서버를 FE/BE 각각 두면 됨.
* Repository 내의 Secret 설정
* 현재는 nest 프로젝트의 build만 진행
* 추후 dockerfile의 수정이 필요함 (redis, db 등 연결 필요)
* react-script로 build 한 내용을 nginx에서 static 하게 제공
- Dockerfile 및 `deploy_dev.yml`에서 jobs의 흐름
> 이 PR merge 이전에 프론트 쪽 package.json 업데이트 된 내용이 먼저 merge 되어야합니다.

2-3 [배포] [배포] docker, github workflows 이용한 dev 서버 배포 자동화

---

.github/workflows/deploy_dev.yml
backend/.gitignore
backend/docker-compose.yml
backend/package.json
backend/src/main.ts

Dockerfile 1개만 사용한다면, backend의 dockerfile 내부에는 redis도 있고, mongodb도 있고, api server도 있어야하는 상황이 되었습니다.
따라서, docker-compose로 각 서비스를 `viewpoint` 네트워크로 묶었습니다.
- ssh-action에서 backend 배포시 docker-compose 사용하도록 변경
- 서버에서 사용할 docker-compose 파일을 작성했습니다.
- 배포 상태 확인

2-4 [배포] [배포] docker-compose redis, db 연결

---

frontend/src/pages/Main/components/KeywordRanking.tsx

인기검색어 UI 개선, 데이터 로딩 시 깜빡임 현상 수정
- 인기검색어 padding 수정하여 텍스트 중앙정렬
- 인기검색어 슬라이딩 클릭 이벤트 범위 수정
- 데이터 로딩 시 UI 깜빡임 이슈 수정
- N/A

[FE] 인기검색어 UI 마이너 수정

---

backend/src/ranking/ranking.module.ts
docker-compose.dev.yml

redis가 외부로부터 flush-all을 당하고 해커가 원하는 값이 redis에 세팅 되는 현상을 발견하여 redis에 비밀번호 설정
* 세팅해놨던 키들이 지속적으로 삭제(flush-all)되는 현상을 발견
* Redis log를 확인하니, DB가 save되는 시점에 flush-all 되는 현상을 확인
* Redis container에서 `keys *` 를 실행해보니, backup1, backup2, backup3, backup4 가 cron 명령어 형태로 세팅됨
* `dump.rdb` 파일을 확인했을 때, 설정하지 않은 key들이 설정되어있음을 확인
* redis에 비밀번호를 설정해놓지 않아 해킹당했다는 여러 글들을 확인하면서 원인을 파악함.
* [참고1](https://gofnrk.tistory.com/122)
* [참고2](https://www.crowdstrike.com/blog/new-kiss-a-dog-cryptojacking-campaign-targets-docker-and-kubernetes/)
* Server 생성시 이전 프로젝트 때 생성해놨던 ACG를 그대로 사용하면서 redis에 사용하고 있던 포트가 public하게 열려있는 상태임을 인지하지 못한 상태였음.
* Redis에 비밀번호를 설정해놓지 않아서 누구나 REDIS_PORT만 알면 redis에 접속 가능한 상태였음.
- #17 fix
* Redis 비밀번호 설정 및 nest application에서 redis 연결시 환경변수로 비밀번호 전달
* Redis의 60초마다 1000개의 key가 변경되었는지 검사하여 save(dump) …

Redis password 설정

---

.github/workflows/deploy_dev.yml

* `./backend` 폴더 내부만 수정되었을 때는, frontend 이미지는 다시 빌드할 필요가 없습니다.
* Container Registry에는 PR number를 태그로하여 이미지가 차곡차곡 쌓이고 있습니다. 
변경점이 없는데도 새로운 태그가 추가되다보니, 어떤 태그가 달린 이미지가 변경점이 있는 이미지인지 확인하기가 어렵습니다.
(변경점이 없을 때에도, 400MB씩 Object Storage의 용량을 차지하는 것은 아닙니다.)
태그(PR Number)를 통해, 변경점이 있는 이미지들에 대해서만 추적관리하고자 하는 것이 목적입니다.
* 사진은 배포된 백엔드 이미지들이 저장되어있는 모습입니다.
* 현재 Container registry와 Object Storage 사용량은 아래와 같습니다.
- `deploy_dev.yml`에 [paths filter](https://github.com/dorny/paths-filter) 적용
- N/A

2-6 [배포] [fix] 불필요한 이미지 빌드 최소화

---

.github/workflows/deploy_dev.yml

`https://github.com/dorny/paths-filter` 에서 [`actions/checkout` step이 필요없다고 이야기한 부분](https://github.com/dorny/paths-filter#conditional-execution)은 `on - pull request` 일 때 입니다.
현재 자동 배포에 사용하고 있는 action은 `on - push` 일 때여서, 해당 스텝이 필요했으나, #39 에서 누락하였습니다.
- `actions/checkout` step 추가
- private repo에서 해당 액션 테스트
- 자동 배포가 정상적으로 작동하기 위해서는 이 PR이 우선적으로 merge 되어야합니다.

 2-6 [배포] [fix] checkout step 추가

---

.github/workflows/deploy_dev.yml

`pull_from_registry`의 실행 순서는 `push_to_registry_be`와 `push_to_registry_fe` 가 모두 실행된 후여야합니다.
하지만, 두 job 중 하나라도 실행되었다면 `pull_from_registry`는 실행되어야합니다.
현재는 backend 폴더와 frontend 폴더가 모두 수정되어야 작동됩니다.
- #46 으로 인한 배포 자동화 막힘 현상 해결
- PR이 머지된 후에는 아래 사진과 같이, 2단계에서의 2개의 job 중 하나라도 완료되면 서버로 배포를 진행합니다.
- N/A

2-6 [배포] [fix] actions 마지막 단계 미실행 현상 해결

---

backend/src/search/pipe/search.dto.ts
backend/src/search/pipe/search.pipe.ts
backend/src/search/search.controller.ts
backend/src/search/search.service.ts

* client에서 항상 query value를 전달해줘야하는 이슈
* query value가 string으로 처리되는 이슈
- `SearchDto` 의 validation 로직 수정
- `KeywordValidation` 에서 2글자 이상인 경우 valid 하도록 처리
- N/A

10-2 [BE] [Fix] query의 default 값 지정

---

frontend/src/components/AutoCompletedList.tsx

자동완성에서 검색어 단어 별로 각각 강조되도록 수정
- 기존에 전체 키워드와 일치하는 부분만 강조되던 기능을 각 단어 별로 강조되도록 변경했습니다.
기존 : 'sun star' 전체 부분이 일치해야 강조
변경 : 'sun'과 'star'가 따로 포함되어 있어도 각각 강조
- 로직에서 더 개선할 수 있는 부분이 있을지, 혹시 예외 상황이 있을 지 조언 부탁드립니다.

7-7 [FE] [fix] 검색어 단어가 여러개일 때 각 단어 별 강조 기능 추가

---

frontend/src/pages/Main/components/KeywordRanking.tsx

- 인기검색어 api 호출 로직 react-query로 변경
- 인기검색어 클릭 시 검색 페이지로 이동
- 인기검색어 api 호출 로직을 react-query로 변경했습니다.
- 인기검색어 클릭 시 해당 키워드로 검색된 페이지로 이동합니다.
- 인기검색어 api 호출에서 오류 발생 시 3번 retry 후 인기검색어 부분에 에러 메시지가 뜨도록 설정했습니다.

4-6 [FE] [메인 - 인기 검색어] 인기검색어 클릭 시 해당 검색어로 검색된 페이지로 이동하고, 검색결과 데이터를 요청하고 받아온다.

---

frontend/.eslintrc.json
frontend/src/constants/path.ts
frontend/src/pages/Main/components/KeywordRanking.tsx
frontend/src/style/GlobalStyle.tsx

인기검색어 클릭시 검색결과 페이지로 이동하는 방식을 수정했습니다.
기존 : 각 키워드에 onClick 이벤트를 달고 click 시 `navigate`를 이용하여 페이지 이동
수정 : 각 키워드에 `Link`를 적용하여 페이지 이동
페이지 이동에 react-router-dom을 사용하고 있는데, navigate를 사용하는 것보다 Link 기능을 사용하는 것이 더 직관적으로 페이지 이동을 파악할 수 있고, 코드 양을 줄일 수 있다고 판단하여 수정하였습니다.
- 인기검색어 클릭시 검색결과 페이지로 이동 로직 navigate -> Link로 변경
- GlobalStyle에서 a 요소 기본 스타일 제거
- .eslint.json 파일 주석 제거

4-6 [FE][fix] 인기검색어 클릭시 검색결과 페이지로 이동하는 방식 수정

---

frontend/src/components/Pagination.tsx

refactor: pagination Button에 disabled 속성 추가
- refactor: pagination Button에 disabled 속성 추가
- 이전 리팩터링 PR에 포함되었어야 하는 부분인데 누락하고 머지를 시켜버렸네요... 미안합니다..🙏

refactor: pagination Button에 disabled 속성 추가

---

frontend/src/App.tsx
frontend/src/customHooks/useGraphData.ts
frontend/src/pages/PaperDetail/PaperDetail.tsx
frontend/src/pages/PaperDetail/components/PaperInfo.tsx
frontend/src/pages/PaperDetail/components/ReferenceGraph.tsx

14-3 [FE] [논문 상세 - 네트워크 차트] 검색한 논문과 이를 참조한 논문을 1depth만큼 표현하는 네트워크 그래프를 렌더링 한다.
- 검색한 논문과 참조한 논문들의 관계를 표현하는 네트워크 그래프를 렌더링 합니다.
- 선택된 노드는 star, 서브노드는 square 모양으로 표시됩니다.
- 스크롤 zooming이 가능합니다.
- 마우스 panning이 가능합니다.
- author를 찾을 수 없는 경우 unknown으로 표시됩니다.
- 데모데이를 앞두고 빠른 작업을 위해 몇가지 타입을 any로 처리한 부분이 있습니다. 이는 추후 수정될 예정입니다.

14-3 [FE] [논문 상세 - 네트워크 차트] 검색한 논문과 이를 참조한 논문을 1depth만큼 표현하는 네트워크 그래프를 렌더링 한다.

---

backend/Dockerfile
backend/src/batch/batch.config.ts
backend/src/batch/batch.service.ts
backend/src/batch/batcher.abstract.ts
backend/src/batch/batcher.doi.ts
backend/src/batch/batcher.search.ts
backend/src/search/search.controller.ts
backend/src/search/search.module.ts
backend/src/search/search.service.ts
backend/src/util.ts
frontend/Dockerfile

1. GitHub Actions Fail 오류 수정
2. Request batcher에 대한 로직을 수정
* 파란 상자 안에 있는 부분이 추가되었습니다.
* 키워드로 검색한 논문별로 reference까지 하나씩 탐색하던 로직을 삭제했습니다.
* 사용자로부터 reference에 대한 doi를 직접 검색요청받았을 때, doiQueue에 검색 요청이 들어가며 해당 논문의 reference까지 탐색합니다.
- `Dockerfile` BE / FE 수정 (npm i -> npm ci) #87
- Too many request를 최대한 방지하기 위해 batch 설정 변경
- default `TIME_INTERVAL` 을 3초에서 1초로 줄이고, batch 한 단위가 끝나야만 다음 batch를 실행할 수 있도록 함
- Too many request 발생시, `RESTART_INTERVAL` 만큼 요청을 보내지 않음 (Batcher 내부에 block 변수를 static하게 선언)
- crossref에 요청을 보낼 때, 1분 정도가 걸릴 때도 있고, 재요청 보냈을 때 요청이 빨리 올 것이라는 기대를 할 수 없어서, axios timeout 시간을 1분으로 변경 (+ sort=is-referenced-by-count 쿼리를 제외해야하나 고민 중 이지만, 해당 keyword에 대해 너무 많은 검색결과가 나올 수 있는 경우, 1개의 키워드에 대한 결과를 수집하는데만 4-5시간 정도 걸릴 것으로 예상되어, 우선 순위가 높은(많이 인용당한) 논문 순으로 우리 DB로 가져오는 것은 필요한 작업이 아닐까하는 생각이 됨)
- redis에 …

13-6 [BE] [Fix] Request batcher 로직 수정

---

backend/src/search/search.service.ts

정렬 기준에 citations를 추가했습니다.
- 1순위, query에 해당하는 score 내림차순
- 2순위, citations 내림차순
- `esService.search` 에 `sort` 추가
* [Elasticsearch Docs 참고](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html)
- N/A

7-4 [BE] [Fix] 검색결과 정렬 기준 변경

---

backend/src/ranking/ranking.service.ts
backend/src/search/search.controller.ts

https://github.com/boostcampwm-2022/web18-PRV/issues/86
해당 이슈에 관한 수정 사항입니다.
- search.controller 의 논문의 list의 개수에 따라 예외처리 하는 로직을 살짝 변경하였습니다.
- page가 total page 이상으로 요청하지만, totalpage가 0인 경우는 제외하였습니다.
- 검색결과가 없는경우 throw 404error를 처리 하던 부분을 삭제하고 빈 리스트를 response하여 front측에서 빈 리스트를 처리하도록 다시 변경하였습니다.

[Fix/pagination]- 검색결과가 없는 경우 404 error내는 오류 수정

---

frontend/public/index.html
frontend/src/components/Footer.tsx
frontend/src/components/search/Search.tsx
frontend/src/pages/PaperDetail/components/PaperInfo.tsx
frontend/src/pages/SearchList/components/Paper.tsx
frontend/src/utils/format.ts

title에 포함된 html tag 제거, author & title 길이제한, 오타수정
- title에 포함된 html tag 부분을 space 한칸으로 교체 했습니다.
- paperInfo내에서의 title 길이도 list와 동일한 길이로 제한했습니다.
- authors는 3줄까지만 보여집니다.
- author -> Author(s), published -> Published 로 용어 수정되었습니다.
- lang=en -> lang=ko로 수정했습니다
- N/A

[Hotfix] title에 포함된 html tag 제거, author & title 길이제한, 오타수정

---

backend/src/search/search.controller.ts
backend/src/search/search.service.ts

Elasticsearch에 참조 논문에 대한 데이터는 없는 경우가 종종 있습니다.
이 때는 불완전한 정보를 그대로 보여주기 보다는, crossref API를 사용하는 것으로 로직을 변경했습니다.
- 불완전하다고 판단될 경우, throw error
- error시 crossref에 데이터 요청
- N/A

[HotFix]  Elasticsearch 데이터가 불완전할 때 crossref API call

---

frontend/src/App.tsx
frontend/src/hooks/graph/useGraphData.ts
frontend/src/hooks/graph/useNodeUpdate.ts
frontend/src/pages/PaperDetail/PaperDetail.tsx
frontend/src/pages/PaperDetail/components/PaperInfo.tsx
frontend/src/pages/PaperDetail/components/ReferenceGraph.tsx

번들 경량화를 위해 라우트별로 코드 스플리팅을 적용했으며 graph 관련 기능 개선 및 citations scale 상수를 변경했습니다.
- react lazy + suspence로 코드 스플리팅 적용
- paper info에 있는 reference 클릭시에도 노드 추가 이벤트 동일하게 적용
- citations -> color scale 범위 조정
- 자식노드 클릭시 api 호출 로직 react-query로 캐싱되게 수정 + suspence 해제
- doi 없는 논문 disabled 처리
- crossRef로 바로 요청을 보내는 경우, referenceList 내부 값들이 완전하지않은 경우를 고려해 변경된 로직
1. 논문 key는 항상 소문자로 변환하여 저장합니다.
2. 정보가 완전하지 않은 자식노드를 클릭했을 때, 해당 노드의 정보 전체가 갈아끼워집니다. 
react-query로 요청을 보낼때마다(해당페이지에서 노드를 추가할 때마다) 깜빡이는 현상이 있어 suspence는 잠시 해제했습니다. 다만 이 경우 페이지 첫 진입시 loader가 돌지 않아 느린 네트워크 환경에서 로더없는 빈 화면이 잠시 노출되는 상황이 생길 수 있습니다. 이 때
1. optimistic update로 Ui만 제공하여 이 현상을 어느정도 절충할지
2. 첫 api 호출만 따로 axois 요청을보내 loader를 노출하는 로직을 작성할지
3. 혹은 새로운 키 하나를 더 만들어 react-query에서 분기처리를 할지
고민이 필요한데, 의견주시면 감사하겠습니다. 그 외 다른 의견도 좋습니다.

[Refactor] 코드 스플리팅 적용, graph 관련 기능 개선 및 상수 변경

---

frontend/Dockerfile

* #105 의 frontend Dockerfile을 수정하지 않아 build가 fail 하는 문제를 수정합니다.
- Dockerfile 내에 robots.txt 삭제
- 빌드가 실패하는 문제가 자주 있지는 않지만, 한번 실패하면 다시 PR을 날려야되는 문제가 있네요.
- 로컬에서 빌드 테스트를 한번 해보고 PR을 올려도 되긴 하지만, 빌드했던 이미지들이 차지하는 용량으로인해 삭제도 해줘야하고 귀찮은 부분이 조금 있습니다.
- PR을 날린 시점에 이미지를 container registry에 push 하고, merge 될 때 배포되는 서버에 접속해서 docker compose pull 하는 방식을 사용할 순 있을 것 같습니다.
- 이렇게했을 때 장점
- PR을 머지하는 시점에서 항상 성공한 빌드 이미지만 사용할 수 있어요.
- PR 올라갈 때 이미지 빌드 CI가 돌아서, merge 하는 시점에는 배포되는 서버가 이미지를 pull만 하면 되므로 배포에 소요되는 시간이 체감상 확 줄어듭니다.
- 예상되는 문제점
- Container registry에 이미지가 꽤 많이 쌓일 것 같습니다. (PR 날린 이후의 커밋들에 대해서도 빌드해야하니까)
- docker compose pull 할 때 어떤 이미지를 가져와야하는지(어떤 tag인지) 알아와야하는 로직이 필요한데 바로 떠오르진 않네요.
- 다른 팀들은 어떻게 하고 있나 조사를 한번 해보겠습니다~

2-5 [Fix] Frontend Dockerfile 수정

---

frontend/src/api/api.ts

서버 요청 axios api의 BASE_URL을 환경변수로 설정했습니다.
로컬에 `.env.development.local` 파일, 배포 시 `.env.production` 파일 생성 후 `REACT_APP_BASE_URL=` 환경변수 추가가 필요합니다.
- 서버 요청 api BASE_URL 환경변수 설정
- N/A

[fix] Frontend api BASE_URL 환경변수 설정

---

frontend/src/hooks/graph/useGraphData.ts

referenceLink 없을 때 자식노드가 업데이트 되지않는 오류를 해결했습니다.
- referenceLink 없을 때 자식노드가 업데이트 되지않는 오류를 해결했습니다. link의 변경사항이 없어도 state를 갈아끼워줘야 simulation이 다시 돌면서 노드에 반영되므로 항상 link가 업데이트되게 로직을 수정했습니다.
- #111 fix
- N/A

[Fix] referenceLink 없을 때 노드 업데이트 되지않는 오류 해결

---

backend/src/batch/tests/batch.service.spec.ts
backend/src/batch/tests/batcher.spec.ts
backend/src/ranking/ranking.service.ts
backend/src/search/tests/search.controller.spec.ts

입력값을 2글자 미만인 경우를 validation pipe에서 막고 있었으나, redis검증 로직에서 2글자 이하인 경우를 에러를 내는 설계 오류가 있었습니다.
- 2글자 미만일시 return으로 변경하였습니다.

[Fix/redis-insert]- 2글자 이하 입력 시 redis에서 error를 throw하는 에러 수정

---

frontend/public/index.html
frontend/src/App.tsx
frontend/src/api/api.ts
frontend/src/components/search/AutoCompletedList.tsx
frontend/src/components/search/Search.tsx
frontend/src/hooks/graph/useGraphData.ts
frontend/src/pages/Main/Main.tsx
frontend/src/pages/Main/components/KeywordRanking.tsx
frontend/src/pages/PaperDetail/PaperDetail.tsx
frontend/src/pages/PaperDetail/components/PaperInfo.tsx
frontend/src/pages/PaperDetail/components/ReferenceGraph.tsx
frontend/src/pages/SearchList/SearchList.tsx
frontend/src/pages/SearchList/components/Paper.tsx
frontend/src/pages/SearchList/components/SearchResults.tsx
frontend/src/utils/format.tsx

doi로 검색시 바로 상세페이지로 이동하는 기능을 추가했습니다.
- doi로 검색시 바로 상세페이지로 이동하는 기능을 추가했습니다. 검색하려는 키워드가 doi 포맷이면 `GET /search/paper` 요청을 보내고, 에러 반환시 search-list 페이지로, 성공시 detail 페이지로 이동합니다.
- doi 검색시 `GET /search/paper` call을 한번만 하기위해 detail 페이지로 라우트 이동시 이전에 받은 doi 요청결과를 state로 가져갑니다.
- og tag를 업데이트 했습니다.
- 자동완성 목록에 tag 제거로직 누락되어있던부분 수정했습니다.
- doi가 유효한지 확인하는동안 로딩을 어떻게 보여줄지에 대한 논의가 필요합니다.

[Feature] doi로 검색시 바로 상세페이지 접근하는 기능 추가

---

backend/src/search/search.service.ts

- referenceList의 key는 DOI일 수도, DOI가 아닐 수도 있습니다.
- crossref에서는 key에 중복된 값을 전달해주기도 합니다.
- 우리 db에도 references에 중복된 item이 배열로 들어있을 수 있습니다.
- `keysTable: {[key: string]: boolean}` 을 만들어서 중복되는 key이면 전달하지 않음.
- N/A

14-11 [BE] [논문 상세 - 네트워크 차트] 논문 reference의 중복 키 제거

---

frontend/src/icons/XIcon.tsx

XMark 아이콘 이름을 XIcon으로 수정하면서 수정이 완벽하지 않아 FE 빌드가 Fail하는 사항 수정
- XIcon 컴포넌트 export 오류 수정
- XMark -> XIcon 파일 이름 수정
* 다른 FE PR 머지 이전에 머지되어야 하는 PR입니다.

[hotfix][FE] XIcon export 오류 수정

---

frontend/src/components/IconButton.tsx
frontend/src/components/search/RecentKeywordsList.tsx
frontend/src/components/search/Search.tsx
frontend/src/icons/XIcon.tsx
frontend/src/icons/index.ts

최근검색어를 삭제하는 기능을 추가했습니다. 
hoveredIndex가 hover될 수 있는 index 범위를 넘을 경우, -1로 초기화되어 hover되지 않은 초기상태로 돌아갑니다.
- 최근검색어를 삭제하는 기능을 추가했습니다. 
- hoveredIndex가 hover될 수 있는 index 범위를 넘을 경우, -1로 초기화되어 hover되지 않은 초기상태로 돌아갑니다.
- N/A

[FE] [Fix, Feature] 최근검색어 삭제기능, hover 개선

---

backend/src/search/search.service.ts

띄어쓰기 포함해도 검색 됩니다.
- keyword가 encode되어 들어오고 있어서 띄어쓰기가 '%20' 으로 검색되고 있었습니다. -> decode
- query 내부에 match_bool_prefix를  match_phrase_prefix로 수정했습니다.
- [match_phrase_prefix](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase-prefix.html)
- author -> authors로 수정했습니다.
- N/A

[BE] elasticsearch 검색 로직 수정

---

backend/src/ranking/ranking.controller.ts
backend/src/ranking/tests/ranking.controller.spec.ts
backend/src/search/search.controller.ts
backend/src/search/search.service.ts
backend/src/util.ts

정확한 키워드로 논문을 검색할 경우, 검색결과가 없으면 우리 서비스에 대한 신뢰도가 떨어질 수 있습니다.
이 때 crossref 검색 로직을 사용합니다.
- elasticsearch로 검색했을 때, 아무런 결과가 없을 경우(우리 db에 해당 논문이 없을 경우) crossref API를 사용하여 검색합니다. (이전 로직 사용)
- 이 PR로 인해 too many request가 뜰 수도 있지만, 꽤 많은 사용자가 몰려야 하겠습니다. (1초에 요청 50회 이상)
- `keyword-ranking/insert` 를 삭제했습니다.
- N/A

[BE] keyword 검색시 crossref로 검색하는 로직 추가

---

frontend/src/App.test.tsx
frontend/src/components/Footer.tsx

Footer 이메일 수정했습니다.
- vp.prv@gmail.com -> viewpoint.prv@gmail.com
- N/A

Footer 이메일 수정

---

frontend/src/components/IconButton.tsx
frontend/src/components/search/AutoCompletedList.tsx
frontend/src/components/search/RecentKeywordsList.tsx
frontend/src/icons/InfoIcon.tsx
frontend/src/pages/Main/components/KeywordRanking.tsx
frontend/src/pages/Main/components/RankingSlide.tsx
frontend/src/pages/PaperDetail/components/InfoTooltip.tsx
frontend/src/pages/PaperDetail/components/PaperInfo.tsx
frontend/src/pages/SearchList/components/Paper.tsx
frontend/src/pages/SearchList/components/SearchResults.tsx
frontend/src/style/styleUtils.ts

메인페이지에서 키워드가 한 줄 이상일 때 박스 밖으로 벗어나는 현상 수정 및 말줄임표 적용
- 인기검색어, 최근검색어 키워드가 한 줄 이상일 때 말줄임표 적용
- 자동완성, 검색목록 타이틀 line-height 수정
- 상세페이지 DOI가 길면 박스 밖으로 벗어나는 현상 수정
- 인기검색어, 최근검색어가 키워드가 길 때 정상적으로 말줄임표가 적용되는지 테스트 부탁드립니다. 현재 dev api server에 긴 키워드를 인기검색어로 올려두었습니다.
- 다음과 같이 적용되어야 합니다.

[Hotfix] 텍스트 버그 수정

---

frontend/src/hooks/graph/useGraph.ts
frontend/src/hooks/graph/useGraphEmphasize.ts
frontend/src/pages/PaperDetail/components/PaperInfo.tsx

그래프 텍스트와 강조되는 링크가 더 잘 보이도록 가시성을 개선했습니다.
스크롤바의 가시성을 개선했습니다.
- 그래프상의 텍스트에 bold를 적용했습니다.
- 선택된 노드와 자식노드의 텍스트의 색상이 진한노랑(secondary2)로 변경됩니다.
- 강조되는 링크의 두께가 더 굵어졌습니다. (0.8px -> 1.5px)
- 스크롤할 컨텐츠가 있는 경우 스크롤바가 항상 보이게 됩니다.
- N/A

[FE] 그래프 가시성 개선

---

frontend/src/pages/PaperDetail/components/ReferenceGraph.tsx

최초 렌더링시 web worker를 3개씩 생성하는 문제를 해결했습니다.
- 최초 렌더링시 web worker를 3개씩 생성하는 문제를 해결했습니다.
- N/A

fix: 최초 렌더링시 중복된 web worker 생성 막기
